import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/molecules/Navbar";
import Sidebar from "./_components/molecules/Sidebar";
import RightSidebar from "./_components/organisms/RightSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body className="w-full h-full overflow-x-hidden">
        <Navbar />
        <div className="flex w-full min-h-screen overflow-x-hidden">
          <Sidebar />
          <main className="flex-1 p-6 overflow-x-auto">{children}</main>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
